"""project_cotraitants link

Revision ID: 05c964b84c3e
Revises: 8d4e41606040
Create Date: 2026-06-13 18:29:38.983051
"""
from alembic import op
import sqlalchemy as sa


revision = '05c964b84c3e'
down_revision = '8d4e41606040'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_cotraitants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('cotraitant_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('lot', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cotraitant_id'], ['cotraitants.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_cotraitants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_cotraitants_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_cotraitants_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_cotraitants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_cotraitants_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_cotraitants_id'))

    op.drop_table('project_cotraitants')
    # ### end Alembic commands ###
