"""add analyses_period

Revision ID: 8d4e41606040
Revises: db24559dfd46
Create Date: 2026-06-13 14:03:45.014969
"""
from alembic import op
import sqlalchemy as sa


revision = '8d4e41606040'
down_revision = 'db24559dfd46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analyses_period', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('analyses_period')

    # ### end Alembic commands ###
