"""document project link + folder

Revision ID: 9734d3292bda
Revises: 05c964b84c3e
Create Date: 2026-06-13 18:33:36.394155
"""
from alembic import op
import sqlalchemy as sa


revision = '9734d3292bda'
down_revision = '05c964b84c3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('folder', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_column('folder')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
