"""initial schema

Revision ID: db24559dfd46
Revises: 
Create Date: 2026-06-13 13:49:34.623923
"""
from alembic import op
import sqlalchemy as sa


revision = 'db24559dfd46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('plan', sa.Enum('starter', 'pro', 'business', name='plantype'), nullable=True),
    sa.Column('analyses_used_this_month', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('siret', sa.String(length=20), nullable=True),
    sa.Column('code_ape', sa.String(length=10), nullable=True),
    sa.Column('forme_juridique', sa.String(length=50), nullable=True),
    sa.Column('capital', sa.String(length=50), nullable=True),
    sa.Column('representant_legal', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('tva_intracom', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('ca_n1', sa.Float(), nullable=True),
    sa.Column('ca_n2', sa.Float(), nullable=True),
    sa.Column('ca_n3', sa.Float(), nullable=True),
    sa.Column('effectif', sa.Integer(), nullable=True),
    sa.Column('qualifications', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_id'), ['id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('contact_type', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_id'), ['id'], unique=False)

    op.create_table('cotraitants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('siret', sa.String(), nullable=True),
    sa.Column('code_ape', sa.String(), nullable=True),
    sa.Column('forme_juridique', sa.String(), nullable=True),
    sa.Column('representant_legal', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('tva_intracom', sa.String(), nullable=True),
    sa.Column('ca_n1', sa.Float(), nullable=True),
    sa.Column('ca_n2', sa.Float(), nullable=True),
    sa.Column('ca_n3', sa.Float(), nullable=True),
    sa.Column('effectif', sa.Integer(), nullable=True),
    sa.Column('qualifications', sa.String(), nullable=True),
    sa.Column('specialites', sa.String(), nullable=True),
    sa.Column('codes_cpv', sa.String(), nullable=True),
    sa.Column('departement', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cotraitants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotraitants_id'), ['id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('administratif', 'fiscal', 'assurances', 'qualifications', 'autre', name='doccategory'), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('alert_30_sent', sa.Boolean(), nullable=True),
    sa.Column('alert_7_sent', sa.Boolean(), nullable=True),
    sa.Column('alert_day_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    op.create_table('matching_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('daily_rate_min', sa.Float(), nullable=True),
    sa.Column('penalty_max', sa.Float(), nullable=True),
    sa.Column('max_distance_km', sa.Integer(), nullable=True),
    sa.Column('departments', sa.JSON(), nullable=True),
    sa.Column('market_types', sa.JSON(), nullable=True),
    sa.Column('lot_types', sa.JSON(), nullable=True),
    sa.Column('exclude_no_variants', sa.Boolean(), nullable=True),
    sa.Column('exclude_no_rse', sa.Boolean(), nullable=True),
    sa.Column('exclude_no_subcontracting', sa.Boolean(), nullable=True),
    sa.Column('excluded_keywords', sa.Text(), nullable=True),
    sa.Column('nogo_threshold', sa.Integer(), nullable=True),
    sa.Column('go_threshold', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('matching_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matching_criteria_id'), ['id'], unique=False)

    op.create_table('matching_criteria_ext',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('budget_min', sa.Float(), nullable=True),
    sa.Column('budget_max', sa.Float(), nullable=True),
    sa.Column('ca_ratio_max', sa.Float(), nullable=True),
    sa.Column('avance_min', sa.Float(), nullable=True),
    sa.Column('delai_paiement_max', sa.Integer(), nullable=True),
    sa.Column('max_distance_km', sa.Integer(), nullable=True),
    sa.Column('departements', sa.String(), nullable=True),
    sa.Column('regions', sa.String(), nullable=True),
    sa.Column('types_marche', sa.String(), nullable=True),
    sa.Column('procedures_acceptees', sa.String(), nullable=True),
    sa.Column('lot_min', sa.Float(), nullable=True),
    sa.Column('codes_cpv', sa.String(), nullable=True),
    sa.Column('qualifications', sa.String(), nullable=True),
    sa.Column('certifications', sa.String(), nullable=True),
    sa.Column('specialites', sa.String(), nullable=True),
    sa.Column('effectif_max_marche', sa.Integer(), nullable=True),
    sa.Column('penalty_max', sa.Float(), nullable=True),
    sa.Column('garantie_max', sa.Float(), nullable=True),
    sa.Column('retenue_garantie_max', sa.Float(), nullable=True),
    sa.Column('delai_reponse_min', sa.Integer(), nullable=True),
    sa.Column('excluded_keywords', sa.String(), nullable=True),
    sa.Column('go_threshold', sa.Integer(), nullable=True),
    sa.Column('nogo_threshold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('matching_criteria_ext', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matching_criteria_ext_id'), ['id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('nouveau', 'en_cours', 'envoye', 'gagne', 'perdu', 'abandonne', name='projectstatus'), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('go_decision', sa.String(length=20), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('dce_file_key', sa.String(length=500), nullable=True),
    sa.Column('workflow', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)

    op.create_table('generated_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('filled_data', sa.JSON(), nullable=True),
    sa.Column('manual_edits', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_docs_id'), ['id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('type', sa.Enum('devis', 'facture', 'avoir', name='invoicetype'), nullable=False),
    sa.Column('status', sa.Enum('brouillon', 'envoye', 'accepte', 'en_attente', 'paye', 'en_retard', name='invoicestatus'), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_address', sa.Text(), nullable=True),
    sa.Column('client_siret', sa.String(length=20), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('subtotal_ht', sa.Float(), nullable=True),
    sa.Column('tva_rate', sa.Float(), nullable=True),
    sa.Column('tva_amount', sa.Float(), nullable=True),
    sa.Column('total_ttc', sa.Float(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('generated_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_docs_id'))

    op.drop_table('generated_docs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('matching_criteria_ext', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matching_criteria_ext_id'))

    op.drop_table('matching_criteria_ext')
    with op.batch_alter_table('matching_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matching_criteria_id'))

    op.drop_table('matching_criteria')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))

    op.drop_table('documents')
    with op.batch_alter_table('cotraitants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cotraitants_id'))

    op.drop_table('cotraitants')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_id'))

    op.drop_table('companies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
